# Generated by Django 5.0.4 on 2024-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartamento",
            old_name="lista_de_tags",
            new_name="tags",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="apartamento",
        ),
        migrations.AddField(
            model_name="apartamento",
            name="bloco",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="condominio",
            name="cnpj",
            field=models.CharField(default="", max_length=19, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="num_tag",
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddConstraint(
            model_name="apartamento",
            constraint=models.UniqueConstraint(
                fields=("condominio", "bloco", "num_do_apto"), name="unique_apto"
            ),
        ),
    ]
